// <auto-generated />
using CalcExp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalcExp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240303195324_Users-configuration-with-update-AppDBContext")]
    partial class UsersconfigurationwithupdateAppDBContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalcExp.User", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Abdulrahman_140141",
                            Password = "Abdulrahman_140141"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
